### ISSUE TITLE
Designating Braille Math Code -- may be a US-centric issue

### ISSUE THREAD

**Issue by mrhunsaker** [daisy/ebraille#25] opened 2022-09-20 14:03 UTC
related to #19  

I see a need to flag a file as being UEB Technical or Nemeth within a UEB Context for Math and Scientific texts. Unfortunately in the United States we leave the decisions whether to use UEB Technical or Nemeth to the state or University being attended.

This can be accomplished within Metadata, and should also be clear as to whether the material is human transcribed or through an automated process.

**Comment by jrbowden** [comment] 2022-09-21 08:26
There are several other technical codes used around the world, but yes, I agree information about the technical code used wwould be helpful.

**Comment by mhorspool** [comment] 2022-09-26 20:07
I see the need, but would favour inferring it rather than specifying it outright. I.E. #20 would either specify just UEB, or UEB and Nemeth. If it specifies UEB and Nemeth, the inferance is Nemeth within a UEB context. If it specifies just UEB, the inferance would be that the UEB technical code is being used.

**Comment by avneeshsingh** [comment] 2022-09-27 11:45
I think we can assign it medium priority. It may be addressed with metadata in future.

**Comment by wfreeman-aph** [comment] 2022-09-27 14:37
One question that comes up here is whether we want to include braille code switches as markup within the document. Then we're not dealing with metadata.

**Comment by mhorspool** [comment] 2022-09-27 21:34
I wouldn't want reading tools to have to look through the markup to identify which codes are in use. If we decide to include code switches as markup I would prefer this be considered as a separate use case.

**Comment by wfreeman-aph** [comment] 2022-09-28 12:01
Good point. I wasn't clear in my comment and what I should have said was include braille code switches as markup _and_ as metadata. The use of semantic markup is issue #28 and includes braille code switches.

**Comment by mrhunsaker** [comment] 2022-09-28 15:42
I agree with @mhorspool here that we can put UEB and UEB+Nemeth in metadata as UEB+Nemeth has Nemeth indicators as part of the code.  At present the movement for a unified Literary Nemeth code has not gained any traction so I think we have finally settled on UEB and UEB+Nemeth as the US Technical options. 

I aso agree with @wfreeman-aph that there is a benefit of a switch AND metadata

**Comment by mattgarrish** [comment] 2022-10-07 16:34
The comments I made in https://github.com/daisy/ebraille/issues/27#issuecomment-1271789758 https://github.com/daisy/ebraille/issues/28#issuecomment-1271774574 apply here, too. The case of setting and switching codes suggests the need for attributes, though.

I know you can express braille through language subtags, but off the top of my head I don't know how specific the tags can get. That could be one avenue for expressing this information. Being able to set languages globally and at the element level is also available in all of EPUB, HTML, DTBook, and pub manifest.

**Comment by bertfrees** [comment] 2022-10-10 12:41
> I know you can express braille through language subtags, but off the top of my head I don't know how specific the tags can get.

I believe currently you can only express that the script/writing system is "Brai" ([ISO 15924](https://en.wikipedia.org/wiki/ISO_15924)). In some cases, together with the language ([ISO 639](https://en.wikipedia.org/wiki/ISO_639)) this is enough information to identify the braille code, because some languages only have one braille code. But some languages have multiple braille systems, and most braille systems have multiple variants (e.g. contraction grades). This can currently not be expressed in a BCP 47 language tag. However there is the "Extension T" ([RFC 6497](https://www.rfc-editor.org/rfc/rfc6497)) which was designed to contain this kind of information. ("T" stands for "transformed", "transliterated", "**transcribed**" or "translated".)

I think the e-braille project is the perfect opportunity to:

1. Create an exhaustive list of braille codes and a standard to identify them.
2. Do what is necessary to be able to use these braille codes in "Extension T" tags.

**Comment by Steve-Noble** [comment] 2022-10-19 12:40
I would agree that in any language where different codes for mathematics are in common usage, knowing _which_ math code has been used is going to be a critical indicator for both the educator and the student. This is certainly the case in the USA where either UEB Technical or Nemeth may be employed depending upon your locality.

**Comment by mattgarrish** [comment] 2023-05-08 13:43
> Do what is necessary to be able to use these braille codes in "Extension T" tags.

Ya, I was just reading over the RFC to see how this would work. It's a bit verbose because in most cases you're simply transcribing from the same language.

For BANA Grade 2 braille, for example, you could end up with a tag like this:

> en-t-en-m0-bana-grade2

The "m0" designator is followed by the authority, so in order for this to be perfectly valid, we'd have to register "bana" as an authority in https://github.com/unicode-org/cldr/blob/maint/maint-41/common/bcp47/transform.xml (and also all the other possible authorities, like UEB, Nemeth, etc.).

As far as I can tell, we're be free to set the additional parameters after the authority to whatever we need, but we'd need to standardize these so they don't vary from producer to producer.

**Comment by bertfrees** [comment] 2023-05-09 15:11
@mattgarrish Thanks for looking into it. Yes, it would be somewhat verbose. I guess ideally we'd want something shorter like "en-Brai-bana-grade2" or even "en-bana-grade2", but of course officially registering the authorities and additional parameters is very appealing.

**Comment by mattgarrish** [comment] 2023-05-09 16:09
> I guess ideally we'd want something shorter like "en-Brai-bana-grade2" or even "en-bana-grade2"

Right, and I don't think either is necessarily invalid. The construction of a language tag is defined in RFC 5646 as:

```
langtag       = language
                 ["-" script]
                 ["-" region]
                 *("-" variant)
                 *("-" extension)
                 ["-" privateuse]
```

where the definition of a variant is:

>  Variant subtags are used to indicate additional, well-recognized variations that define a language or its dialects that are not covered by other available subtags.

We could also register these, but they would go directly in the [IANA subtag registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry).

It might be useful to reach out to some of the W3C i18n folks to get their opinions. I don't think the T extension had braille transcription in mind, but it is possible to use it, so it makes it murky which direction we should go in. (A B extension for braille might also make sense.)

The only other option would be to use the private use space, in which case the tag would become:

> en-Brai-x-bana-grade-2

But calling this work "private use" is a bit of a stretch.

**Comment by bertfrees** [comment] 2023-05-09 18:53
Now I'm also unsure what is the best direction to go. It's not totally clear. When I read the definition of a variant:

> Variant subtags are used to indicate additional, well-recognized variations that define a language or its dialects that are not covered by other available subtags.

I would think that the subtag is intended for expressing _language_ information and that information related to the _writing system_ does not really fit there.

But when I read this:

> Dialect or other divisions or variations within a language, its orthography, **writing system**, regional or historical usage, transliteration or other **transformation**, or distinguishing variation MAY be registered as variant subtags.

(emphasis added), then it does seem suited.

**Comment by mattgarrish** [comment] 2023-05-10 02:21
Ya, the RFC is pretty dense. This is where I tend to fall over to some of the W3C explanatory docs, in particular this section makes what we're proposing sound reasonable: https://www.w3.org/International/questions/qa-choosing-language-tags#variants

There's also the doc on [language tags in html and xml](https://www.w3.org/International/articles/language-tags/#variants) which says:

> If you need to express a particular dialectal or script nuance that is not currently available, you should propose a variant subtag or subtags for inclusion in the registry using the registration procedure outlined in RFC 5646.

How you define the prefix seems to define what you are talking about (language versus dialect versus script).

If we define the prefix for "bana" as "en-Brai", for example, I think that's a reasonable way of saying that the braille conforms to bana guidelines. "grade1" could be a variant for any "Brai" prefix, which I believe would allow it to stack onto a bana declaration.

But that's only my best understanding of the issue, not a deeply informed opinion. I wouldn't want to move forward without consulting some experts.

**Comment by jrbowden** [comment] 2023-05-10 08:27
I can't find the issue, but I'm pretty sure we said to split the *language* from the *braille code*.
There are many braille codes which don't have a language as such, any kind of mathematical code being one case. Other cases include the IPA code and music code. I think we need a new ticket to work out a naming scheme for any braille code.

**Comment by mattgarrish** [comment] 2023-05-10 13:05
> Other cases include the IPA code

FYI, there's already a language variant for this:

```
Type: variant
Subtag: fonipa
Description: International Phonetic Alphabet
Added: 2006-12-11
```

**Comment by wfreeman-aph** [comment] 2023-11-15 17:40
Closed as not planned. See #127 for more information.

**Closed by wfreeman-aph** 2023-11-15 17:40 UTC
Labels: question, medium priority, metadata
