### ISSUE TITLE
Include Braille Grade in Metadata

### ISSUE THREAD

**Issue by mhorspool** [daisy/ebraille#19] opened 2022-09-20 13:39 UTC
Extending #18: As a Reader I would like to know the grade(s) of braille contained within the file before I open it so that I can quickly decide whether it will be suitable for me to read.

**Comment by mrhunsaker** [comment] 2022-09-20 13:51
I agree with this. Especially in situations where there are more than 2 grades available (i.e., German)

**Comment by jrbowden** [comment] 2022-09-21 08:20
What happens if the file contains more than one braille code? e.g. the document could be predominantly in, say, UEB grade 2 (contracted), but contain a passage in French, or a mathematical expression, or music in a particular layout ...
Presumably the metadata would either contain the predominant braille code, or should list all codes used?

**Comment by mhorspool** [comment] 2022-09-26 19:56
Good catch. Yes I agree, it should list all codes and grades used, and that involves including the code and grade in the same chunk of metadata so there is no ambiguity about which grade of which code was intended.

To account for codes such as Nemeth and music which don't have grades, we could either make the grade parameter optional, or allow the use of a special value to indicate that the code is gradeless. I would prefer the second approach, as making grade optional leaves the door open for people to be lazy and not specify the grade of braille for codes which do actually have grades.

**Comment by ways2read** [comment] 2022-09-27 14:27
metadata issues are grouped under #27

**Comment by mattgarrish** [comment] 2022-10-07 16:58
The same comments I made in https://github.com/daisy/ebraille/issues/27#issuecomment-1271789758 and https://github.com/daisy/ebraille/issues/25#issuecomment-1271809234 apply here.

**Comment by bertfrees** [comment] 2022-10-10 13:10
See my comment in https://github.com/daisy/ebraille/issues/25#issuecomment-1273256658 about specifying the braille code (including grade) in a BCP 47 language tag.

**Comment by wfreeman-aph** [comment] 2023-12-19 21:15
Duplicate of #117. Has useful info but this comment will link them. Going to close.

**Closed by wfreeman-aph** 2023-12-19 21:15 UTC
Labels: duplicate, use case, High Priority, metadata
