### ISSUE TITLE
Metadata: Designate Math Code

### ISSUE THREAD

**Issue by shepazu** [daisy/ebraille#127] opened 2023-10-31 07:25 UTC
- Requested metadata: Math code
- NLS Element: 
  - `dc:Format`
  - `x-metadata brl:mathCode`
- Notes from GitHub ticket: 
  - Math code should be in markup and the metadata. Could get complex if we use ISO language codes as basis for an exhaustive list of braille codes.
  - NLS uses separate yes/no element for contains math. Could have an option of "none" for mathCode to simplify.

## References:
- Original issue: #25

**Comment by wfreeman-aph** [comment] 2023-11-10 19:01
I think all codes should be included in a single metadata item. It just reads something like `brailleCode` and then all codes are listed, even if only a single character is used from that other code. I don't know that we gain anything by being so specific about math codes, since I don't think the US's math code problem is very common internationally and the problem is solved by this proposed solution.

**Comment by wfreeman-aph** [comment] 2023-11-15 17:40
It was agreed at the 11/14/24 meeting to close this ticket as not planned. This need will be covered by the fact that the file type requires metadata about the braille codes used. Additionally, those braille codes will be listed with the most prevalent code appearing first and then other codes appearing after by prevalence.

**Closed by wfreeman-aph** 2023-11-15 17:40 UTC
Labels: duplicate, question, metadata
